// console.log("Hey, this is first JS program");
let str= ("hello")
console.log(str.length)
console.log(-100/0)
console.log('number' + 23 + 32)
console.log(12 / '6')
console.log(41 + 1 + 'number')
console.log(null + 1)
console.log('five' + + 'two')
console.log("2 && 7")
console.log(+'40' + +'2')
console.log(true + false)
console.log('4px' - 3)
console.log('4' - 3)
console.log('2' + 3 ** 2)
console.log(12 / '6')
console.log(23 + 42 + 'number')
console.log('10' + (5 === 6))
console.log('number' + 15 + 3)
console.log(undefined + 1)
console.log('true' == true)
console.log(false == 'false')
console.log(null == '')
console.log(3 ** (9 / 3))
console.log(!!'false' == !!'true')
console.log(0 || '0' && 1)
console.log(1 < 2 < 3)
console.log('foo'+ + +'bar')
console.log(3 ** 2 / 3)
console.log(1 < 2 > 3)
console.log((+null == false) < 1)
console.log(false && true || true)
console.log(false && (true || true))
console.log((+null == false) < 1 ** 5)
console.log(true)

